version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_demo
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: demo_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq: # <--- AQUI: Alinhado com o 'postgres' (2 espaços de recuo)
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes: # <--- AQUI: No início da linha (coluna 0)
  postgres_data: